### ISSUE TITLE
Database Hello Zuidhorn Service (AWS Datastore)

### ISSUE THREAD

**Issue by maxvisser** [teamforus/app-backend#1]
Amazon Relation Data Store (RDS) has a service for MySQL instances that they maintain as a service.

**Comment by maxvisser** [comment]
I made a MySQL instance on AWS and tried it out. A micro instance costs $0.018 per hour. That is $13,30 a month.

**Comment by maxvisser** [comment]
used the mysql instance in combination with the hello world php example + front end and it works.

**Comment by martijndoornik** [comment]
Considering Amazon is probably better than us in maintaining the database and we need all hands on development, so I agree: the investment in Amazon is worth it.
